version: 0.0
os: linux
files:
  - source: target/*.jar
    destination: /home/ec2-user/simple-java-maven-app

hooks:
  BeforeBlockTraffic:
    - location: scripts/before_block_traffic.sh
      timeout: 300
      runas: root

  BlockTraffic:
    - location: scripts/block_traffic.sh
      timeout: 300
      runas: root

  AfterBlockTraffic:
    - location: scripts/after_block_traffic.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  DownloadBundle:
    - location: scripts/download_bundle.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root

  BeforeAllowTraffic:
    - location: scripts/before_allow_traffic.sh
      timeout: 300
      runas: root

  AllowTraffic:
    - location: scripts/allow_traffic.sh
      timeout: 300
      runas: root

  AfterAllowTraffic:
    - location: scripts/after_allow_traffic.sh
      timeout: 300
      runas: root
